package storage

import (
	"credo/logger"
	"os"
)

const defaultContent = `# !!! WARNING !!!
# This file is automatically generated by CREDO.
# CREDO is a tool designed to create reproducible environments.
---
`

type FileStorage struct {
	Filename string
}

func (s *FileStorage) Write(data []byte) {
	var file *os.File
	defer file.Close()

	// Checks if file exists
	_, err := os.Stat(s.Filename)
	if os.IsNotExist(err) {
		file, err = os.Create(s.Filename)
		if err != nil {
			logger.Get().Fatal(err)
		}
		_, err = file.WriteString(defaultContent)
		if err != nil {
			logger.Get().Fatal(err)
		}
	} else {
		// Opens the file if it already exists
		file, err = os.Open(s.Filename)
		if err != nil {
			logger.Get().Fatal(err)
		}
	}

	content := []byte(defaultContent)
	content = append(content, data...)

	os.WriteFile(s.Filename, content, os.ModeAppend)
	if err != nil {
		logger.Get().Fatal(err)
	}
}

func (s *FileStorage) Read() []byte {
	var file *os.File
	defer file.Close()

	_, err := os.Stat(s.Filename)
	if os.IsNotExist(err) {
		s.Write([]byte(""))
	}

	data, err := os.ReadFile(s.Filename)

	if err != nil {
		logger.Get().Fatal(err)
	}
	return data
}
