name: Build
on:
  push:
    branches: [main]
  release:
jobs:
  build:
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
        platform:
          - darwin
          - linux
          - windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install go
        run: |
          curl -OL https://go.dev/dl/go1.22.1.linux-amd64.tar.gz
          rm -rf /usr/local/go 
          sudo tar -C /usr/local -xzf go1.22.1.linux-amd64.tar.gz
      - name: Test
        run: |
          make test
      - name: Build
        run: |
          GOOS=${{ matrix.platform }} GOARCH=${{ matrix.architecture }} make
      - uses: vimtor/action-zip@v1.2
        with:
          files: credo
          dest: ${{ matrix.platform }}_${{ matrix.architecture }}_credo.zip
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *_credo.zip
