name: Build
on:
  push:
    branches: [main]
  release:
jobs:
  build:
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
        platform:
          - darwin
          - linux
          - windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          check-latest: true
      - name: Debug Git Information
        run: |
          git rev-parse --short HEAD
          git describe --tags --exact-match || echo "No exact tag"
          git status
      - name: Test
        run: |
          make test
      - name: Build
        run: |
          GOOS=${{ matrix.platform }} GOARCH=${{ matrix.architecture }} make
      - uses: vimtor/action-zip@v1.2
        with:
          files: credo
          dest: ${{ matrix.platform }}_${{ matrix.architecture }}_credo.zip
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *_credo.zip
